<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Codeium_Security</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.9" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="MachineLearning\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Logs\" />
    <Folder Include="FeatureExtraction\" />
    <Folder Include="Images\" />
    <Folder Include="tessdata\" />
    <Folder Include="Output\" />
    <Folder Include="TrainingData\" />
    <Folder Include="Utilities\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
